#You must have a t2.medium instance & Ubuntu Server 22.04 LTS (HVM)

---
- name: deploy java project
  hosts: localhost
  become: true
  gather_facts: no
  vars:

    app_name: Spring3HibernateApp.war
    dir_name: project
    project_path: /home/ubuntu/{{ dir_name }}/spring3hibernate
    app_source_path: "{{ project_path }}/target/{{ app_name }}"
    tomcat_user: tomcat
    tomcat_user_password: pass

  tasks:
      - name: create a dir for this task
        file:
            path: /home/ubuntu/{{ dir_name }}
            state: directory
 

      - name: install MySql
        apt:
            name: mysql-server
            state: present

      - name: install java
        apt:
            name: openjdk-11-jdk
            state: present
      
      - name: update the package
        apt:
            update_cache: yes    

      - name: install maven
        apt:
            name: maven
            state: present

      - name: clone the repo
        git:
            repo: https://github.com/opstree/spring3hibernate
            dest: "{{ project_path }}"

      - name: maven dependencies
        command: mvn dependency:resolve
        args:
            chdir: "{{ project_path }}"
        
      - name: maven compile
        command: mvn compile
        args:
            chdir: "{{ project_path }}"

      - name: maven test
        command: mvn test
        args:
            chdir: "{{ project_path }}"

      - name: maven package
        command: mvn package
        args:
            chdir: "{{ project_path }}"

      - name: update & install tomcat
        apt:
            update_cache: true
            name: "{{ item }}"
            state: present
        with_items:
            - tomcat9-admin
            - tomcat9

      - name: Add 'admin-gui' role to tomcat-users.xml
        lineinfile:
            path: /etc/tomcat9/tomcat-users.xml
            line: '<role rolename="admin-gui"/>'
            insertbefore: '</tomcat-users>'
            state: present
        notify:
            - Restart Tomcat

      - name: Add 'manager-gui' role to tomcat-users.xml
        lineinfile:
            path: /etc/tomcat9/tomcat-users.xml
            line: '<role rolename="manager-gui"/>'
            insertbefore: '</tomcat-users>'
            state: present
        notify:
            - Restart Tomcat

      - name: Add 'tomcat' user with roles to tomcat-users.xml
        lineinfile:
            path: /etc/tomcat9/tomcat-users.xml
            line: '<user username="{{ tomcat_user }}" password="{{ tomcat_user_password }}" roles="admin-gui,manager-gui"/>'
            insertbefore: '</tomcat-users>'
            state: present
        notify:
            - Restart Tomcat

      - name: Copy .war files to /var/lib/tomcat9/webapps/
        copy:
            src: "{{ app_source_path }}"
            dest: "/var/lib/tomcat9/webapps/{{ app_name }}"
            remote_src: yes
        notify:
            - Restart Tomcat

  handlers:
      - name: Restart Tomcat
        service:
          name: tomcat9
          state: restarted
